/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hbYUsmt35XF
 */
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"

export function Chat() {
  return (
    <div key="1" className="bg-[#1E1E2D] min-h-screen flex">
      <section className="flex-1 p-6">
        <header className="flex justify-between items-center mb-6">
          <h2 className="text-white text-xl font-semibold">Chat with Russel Hue</h2>
          <span className="text-gray-400 text-sm">13:45</span>
        </header>
        <ScrollArea className="h-[calc(100vh-180px)] mb-6">
          <div className="space-y-4">
            <div className="flex items-end justify-end">
              <div className="bg-[#6C5DD3] text-white rounded-lg p-3 max-w-xs ml-4">
                <p>How does it sound for you?</p>
              </div>
            </div>
            <div className="flex items-end">
              <Avatar>
                <AvatarImage alt="Russel Hue" src="/placeholder.svg?height=40&width=40" />
              </Avatar>
              <div className="bg-[#353945] text-white rounded-lg p-3 max-w-xs mr-4">
                <p>Yes, that sounds good!</p>
              </div>
            </div>
          </div>
        </ScrollArea>
        <div className="flex items-center space-x-2">
          <Input className="flex-1" placeholder="Type your message here..." type="text" />
          <Button className="bg-[#6C5DD3] text-white">
            <SendIcon className="text-white" />
          </Button>
        </div>
      </section>
      <section className="w-1/4 bg-[#2D303E] p-1">
        <header className="flex justify-between items-center mb-2">
          <h2 className="text-white text-sm font-semibold">Chat Topic: Discussing Project Milestones</h2>
          <div className="flex items-center space-x-2">
            <span className="text-gray-400 text-xs">Choose a bot:</span>
            <Select className="w-24">
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select bot" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="bot1">Bot 1</SelectItem>
                <SelectItem value="bot2">Bot 2</SelectItem>
                <SelectItem value="bot3">Bot 3</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </header>
      </section>
    </div>
  )
}


function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
